### ISSUE TITLE
Unhandled Python exception in Mupen64Plus SDL Input plugin window

### ISSUE THREAD

**Issue by zwastik** [mupen64plus/mupen64plus-ui-python#62]
m64py crashes with a Unhandled Python exception error when I select my joystick in the device section in  the Mupen64Plus SDL Input plugin window and then click on close.
m64py 0.2.3-5
mupen64plus 2.5-2
archlinux.
I am using an original ps2 controller with a ps2tousb adapter. The controller works fine.
I patched m64py to include this commit.
https://github.com/alexhenrie/mupen64plus-ui-python/commit/6179216d898b7858b8c1a589ffebd50c504406d9

**Comment by PureTryOut** [comment]
Same issue here, although for me it also crashes when loading games.

I'm using the latest AUR version.

**Comment by conchurnavid** [comment]
Do I see it correctly that you report a problem which is already fixed? (commit 6179216d898b7858b8c1a589ffebd50c504406d9 is already merged in the m64py repository)

Or do you want to say that the commit 6179216d898b7858b8c1a589ffebd50c504406d9 caused the problem?

**Comment by PureTryOut** [comment]
I'm not sure what commit 6179216 did, I just know it crashes for me now with the same error @zwastik reported.

**Comment by zwastik** [comment]
Commit https://github.com/mupen64plus/mupen64plus-ui-python/commit/6179216d898b7858b8c1a589ffebd50c504406d9 fixed a couple of things, however problems still persists as stated above.
I was using archlinux aur version but I decided to test directly from git so to be more up to date.
This issue was also discussed here: https://bbs.archlinux.org/viewtopic.php?id=204248

**Comment by gen2brain** [comment]
Should be fixed in new release. Please file a new issue if it happens again.
